### ISSUE TITLE
Implement a secure Vault settings configuration mechanism

### ISSUE THREAD

**Issue by vkamiansky** [vkamiansky/web-fls-quiz#12]
The settings are passed to a special `POST` Configuration method as a json in the following format:
```
{
  "token": "[<vault token>]",
  "ip": "[<vault ip>]",
  "port": "[<vault port>]"
}
```
Once the post method receives a new configuration it checks the timestamp of the last configuration request and schedules the try-reconfig operation so that it would happen asap but not earlier than 5 minutes after the latest similar operation.
Try-reconfig tries to connect to the Vault. If the auth fails. it does nothing, otherwise it sends an email to the admin containing a confirmation key.
The admin should use the key on a `GET` Configuration method to confirm the configuration change.
All configuration values should be stored in memory in an encrypted form (use Protect/Unprotect dotnet core mechanism).
After this change the only environment value that will be passed to the `docker run` command will be `admin_email`.

**Comment by Shurron** [comment]
In this case, when we start the application, it doesn't know the configuration. But try-reconfig must have Vault connection to know mail server address, port, email and password

**Comment by vkamiansky** [comment]
The try-connect-vault may ask for the settings needed to send an email from Vault. This will be the solution.
